GET http://localhost:3003/todos

#############

POST http://localhost:3003/todo/new
Content-Type: application/json

{
    "text": "By a new laptop"
}

###################

DELETE http://localhost:3003/todo/delete/61ae91c65d084d580a1362c0

#######

PUT http://localhost:3003/todo/complete/61ae91c65d084d580a1362c0

